curso/curso/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from encuestas.admin import admin_site
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^curso-admin/', include(admin_site.urls)),
    #url(r'^grappelli/', include('grappelli.urls')), # para tema grapelli
    url(r'^encuestas/', include('encuestas.urls', namespace='encuestas')),
    # Hacemos que la página predeterminada del proyecto sea el listado de encuestas
    url(r'^$', RedirectView.as_view(url='/encuestas/', permanent=True), name='index'),
    # Utilizamos las vistas predeterminadas para iniciar y cerrar sesión
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {'template_name': 'encuestas/login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}),
]

curso/encuestas/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = [
    # ej: /encuestas/
    url(r'^$', views.VistaIndex.as_view(), name='index'),
    # ej: /encuestas/5
    # Las vistas detalladas genéricas esperan que el argumento se llame 'pk'
    url(r'^(?P<pk>\d+)/$', login_required(views.VistaDetalle.as_view()), name='detalle'),
    # ej: /encuestas/5/resultados
    url(r'^(?P<pk>\d+)/resultados$', views.VistaResultados.as_view(), name='resultados'),
    # ej: /encuestas/5/votar
    url(r'^(?P<id_pregunta>\d+)/votar$', views.votar, name='votar'),
    url(r'^contacto$', views.contacto, name='contacto'),
    url(r'^agregar$', views.VistaCrearPregunta.as_view(), name='agregar'),
    url(r'^(?P<pk>\d+)/editar', views.VistaEditarPregunta.as_view(), name='editar'),
    url(r'^(?P<pk>\d+)/opciones', views.VistaOpciones.as_view(), name='opciones'),
]

curso/encuestas/models.py
from django.db import models
from django.utils import timezone
import datetime

class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=200)
    fe_publicacion = models.DateTimeField('Fecha de Publicación')

    def __str__(self):
        return self.texto_pregunta

    def publicada_recientemente(self, dias=1):
        return self.fe_publicacion >= timezone.now() - datetime.timedelta(days=dias)

    publicada_recientemente.admin_order_field = 'fe_publicacion'
    publicada_recientemente.boolean = True
    publicada_recientemente.short_description = '¿Publicada recientemente?'

    class Meta:
        ordering = ['-fe_publicacion']

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta)
    texto_opcion = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_opcion

    class Meta:
        verbose_name = 'Opción'
        verbose_name_plural = 'Opciones'

curso/encuestas/forms.py
from django import forms
from .models import Pregunta, Opcion
from bootstrap3_datetime.widgets import DateTimePicker
from django.forms.models import inlineformset_factory

class FormContacto(forms.Form):
    asunto = forms.CharField(max_length=100)
    mensaje = forms.CharField(widget=forms.Textarea)
    remitente = forms.EmailField()
    cc_remitente = forms.BooleanField(label='Envíame una copia', required=False)

class FormPregunta(forms.ModelForm):
    class Meta:
        model = Pregunta
        fields = ['texto_pregunta','fe_publicacion']
        widgets = {'texto_pregunta': forms.Textarea(attrs={'rows':3}),
                   'fe_publicacion': DateTimePicker(options={"format": "YYYY-MM-DD",
                                       "pickTime": False})}

FormPreguntaOpciones = inlineformset_factory(
    Pregunta,
    Opcion,
    fields = ('texto_opcion',),
    max_num = 5,
    extra = 5,
)

curso/encuestas/views.py
from .models import Pregunta, Opcion

from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.db.models import F
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic

from django.contrib import messages

from django.core.mail import send_mail
from smtplib import SMTPException
from .forms import *

from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.decorators import login_required
from braces.views import LoginRequiredMixin, GroupRequiredMixin

class VistaIndex(generic.ListView):
    template_name = 'encuestas/index.html'
    context_object_name = 'preguntas_recientes'

    def get_queryset(self):
        return Pregunta.objects.order_by('-fe_publicacion')[:5]

    def get_context_data(self, **kwargs):
        context = super(VistaIndex, self).get_context_data(**kwargs)
        context['titulo'] = 'Listado de Encuestas'
        return context

# Agregamos LoginRequiredMixin para indicar que esta vista requiere autenticación
class VistaDetalle(LoginRequiredMixin, generic.DetailView):
    model = Pregunta
    template_name = 'encuestas/detalle.html'

# En el caso de una vista sencilla (método), podemos usar directamente el decorador login_required
@login_required
def votar(request, id_pregunta):
    pregunta = get_object_or_404( Pregunta, pk=id_pregunta )
    try:
        # Nos aseguramos de que el código de la opción recibida esté dentro de las
        # opciones registradas para la pregunta
        opcion_seleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])

        # Incrementamos la cantidad de votos para la opción seleccionada, pero desde la
        # base de datos directamente
        # opcion_seleccionada.votos += 1 # Esto puede generar problemas en transacciones
                                        # concurrentes
        opcion_seleccionada.votos = F('votos') + 1
        opcion_seleccionada.save()
        # Nota: Lo anterior también podría escribirse de forma compacta como:
        # opcion_seleccionada.update( votos = F('votos') + 1 )

        # Luego de guardar exitosamente, redireccionamos a página de resultados.
        # Utilizamos 'reverse' para obtener de manera reutilizable la URL de la vista a
        # la que queremos redirigir al usuario.
        messages.success(request, "Voto registrado. ¡Gracias por participar!")
        return HttpResponseRedirect(reverse('encuestas:resultados',
                                            kwargs={'pk': pregunta.id}))
    except (KeyError, Opcion.DoesNotExist):
        # En caso de un código incorrecto o faltante de opción, volver a mostrar el formulario
        messages.error(request, "Opción faltante o inválida")
        return render(request, 'encuestas/detalle.html', {
            'pregunta': pregunta,
        })

class VistaResultados(generic.DetailView):
    model = Pregunta
    template_name = 'encuestas/resultados.html'

def contacto(request):
    if request.method == 'POST':
        # Si ya se enviaron datos, se crea una instancia del formulario con ellos
        form = FormContacto(request.POST)
        # Y luego verificamos si es válido
        if form.is_valid():
            try:
                asunto = form.cleaned_data['asunto']
                mensaje = form.cleaned_data['mensaje']
                remitente = form.cleaned_data['remitente']
                cc_remitente = form.cleaned_data['cc_remitente']

                destinatarios = ['homero@example.com']
                if cc_remitente:
                    destinatarios.append(remitente)

                send_mail(asunto, mensaje, remitente, destinatarios)
                messages.success(request, 'Mensaje enviado')
                return HttpResponseRedirect( reverse('encuestas:index') )
            except (ConnectionRefusedError, SMTPException):
                messages.error(request, 'No se pudo enviar el mensaje')

    # Si no se enviaron datos, mostramos el formulario vacío
    else:
        form = FormContacto()

    return render(request, 'encuestas/contacto.html', {'form': form})

# Para las vistas de crear y editar preguntas y opciones, utilizaremos GroupRequiredMixin

class VistaCrearPregunta(GroupRequiredMixin, CreateView):
    model = Pregunta
    form_class = FormPregunta
    template_name = 'encuestas/agregar_pregunta.html'
    success_url = reverse_lazy('encuestas:index')
    group_required = 'puede_administrar_encuestas'

class VistaEditarPregunta(GroupRequiredMixin, UpdateView):
    model = Pregunta
    form_class = FormPregunta
    template_name = 'encuestas/editar_pregunta.html'
    success_url = reverse_lazy('encuestas:index')
    group_required = 'puede_administrar_encuestas'

class VistaOpciones(GroupRequiredMixin, UpdateView):
    '''
    En este ejemplo utilizamos un Formset personalizado para editar las opciones
    correspondientes a una pregunta. Por ello, utilizamos el modelo "padre" (Pregunta),
    y personalizamos los métodos get/post para obtener y guardar la lista de opciones
    '''
    model = Pregunta
    form_class = FormPregunta
    template_name = 'encuestas/editar_opciones.html'
    success_url = reverse_lazy('encuestas:index')
    group_required = 'puede_administrar_encuestas'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        opciones_form = FormPreguntaOpciones(instance=self.object)
        return self.render_to_response(
            self.get_context_data(opciones_form=opciones_form,))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        opciones_form = FormPreguntaOpciones(request.POST, instance=self.object)
        if opciones_form.is_valid():
            opciones_form.save()
            messages.success(request, 'Opciones guardadas')
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(request, 'No se pudieron guardar las opciones')
            return self.render_to_response(
                self.get_context_data(opciones_form=opciones_form,))

curso/encuestas/templates/encuestas/agregar_pregunta.html
{% extends 'encuestas/base.html' %}

{% block extra-head %}
    {{ form.media }}
{% endblock%}

{% block contenido %}

{% load bootstrap3 %}

<h2>Agrega una nueva pregunta</h2>

<form action="{% url 'encuestas:agregar' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "floppy-disk" %} Agregar Pregunta
    </button>
    {% endbuttons %}
</form>

{% endblock contenido %}

curso/encuestas/templates/encuestas/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>{{ titulo | default:"Encuestas" }}</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'encuestas/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'encuestas/css/estilos-personalizados.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'encuestas/js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'encuestas/js/bootstrap.min.js' %}"></script>
    {% block extra-head %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Mostrar/ocultar navegación</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'encuestas:index' %}">Encuestas</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                {% block navegacion %}
                <ul class="nav navbar-nav">
                    {% block navegacion-elementos %}{% endblock %}
                    <li>
                        <a role="button" data-toggle="modal" data-target="#contacto">Contacto</a>
                    </li>
                    <li>
                        <a href="{% url 'admin:index' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            Usuarios y grupos
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'curso-admin:index' %}">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            Sitio administrativo
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_anonymous %}
                    <li><a href="{% url 'django.contrib.auth.views.login' %}">
                        {% bootstrap_icon 'log-in' %} Iniciar sesión</a></li>
                    {% else %}
                    <li><a href="#">{% bootstrap_icon 'user' %} Hola, {{ user }}</a></li>
                    <li><a href="{% url 'django.contrib.auth.views.logout' %}">
                        {% bootstrap_icon 'log-out' %} Salir</a></li>
                    {% endif %}
                </ul>
                {% endblock %}
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
            <img class="pull-right img-responsive" src="{% static 'encuestas/img/django-logo.png' %}" alt="Logo">
            {% block encabezado %}
            <h1>Encuestas</h1>
            <p>Aplicación de demostración en curso Fundamentos de Django</p>
            {% endblock %}
        </div>

        <section id="contenido">
            {% bootstrap_messages %}

            {% block contenido %}{% endblock %}
        </section>
        <section id="contacto" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"
                                aria-label="Cerrar"><span aria-hidden="true">&times;</span></button>
                        <h2 class="modal-title">Contacto</h2>
                    </div>
                    <div class="modal-body">
                    {% include 'encuestas/direccion.html' %}
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-primary" href="{% url 'encuestas:contacto' %}">Enviar mensaje</a>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="text-muted text-center">Pie de página</p>
        </div>
    </footer>

  </body>
</html>

curso/encuestas/templates/encuestas/contacto.html
{% extends 'encuestas/base.html' %}

{% block contenido %}

{% load bootstrap3 %}

<h2>¡Déjanos tu mensaje!</h2>

<form action="{% url 'encuestas:contacto' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "send" %} Enviar
    </button>
    {% endbuttons %}
</form>

{% endblock contenido %}

curso/encuestas/templates/encuestas/detalle.html
{% extends 'encuestas/base.html' %}
{% load bootstrap3 %}

{% block encabezado %}
<h1>Detalle de Encuesta: {{ pregunta.texto_pregunta|truncatewords:5|escape }}...</h1>
{% endblock encabezado %}

{% block contenido %}

<div class="panel panel-primary">
    <div class="panel-heading">¡Participe!</div>
    <div class="panel-body">
        <h2>{{ pregunta.texto_pregunta|escape }}</h2>

        <form action="{% url 'encuestas:votar' pregunta.id %}" method="post">
            {% csrf_token %}
            {% for opcion in pregunta.opcion_set.all %}
                <div class="radio">
                    <label>
                        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}"
                               value="{{ opcion.id }}">
                        {{ opcion.texto_opcion }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Votar</button>
            <a class="btn btn-info" href="{% url 'encuestas:resultados' pregunta.id %}">
                Ver resultados
            </a>
            <a class="btn btn-default" href="{% url 'encuestas:editar' pregunta.id %}">
                {% bootstrap_icon "pencil" %} Editar Pregunta
            </a>
            <a class="btn btn-default" href="{% url 'encuestas:opciones' pregunta.id %}">
                {% bootstrap_icon "pencil" %} Editar Opciones
            </a>
        </form>
    </div>
</div>

{% endblock contenido %}

curso/encuestas/templates/encuestas/direccion.html
<address>
{% filter linebreaksbr %}
    <strong>Homer J. Simpson</strong>
    742 Evergreen Terrace
    Springfield
    <abbr title="Teléfono">T:</abbr> (123) SIMPSONS - (123) {{ 'SIMPSONS'|phone2numeric }}
    <abbr title="Móvil">M:</abbr> (123) 456-7890
{% endfilter %}
</address>

curso/encuestas/templates/encuestas/editar_opciones.html
{% extends 'encuestas/base.html' %}
{% load bootstrap3 %}

{% block contenido %}

<h2>Editar Opciones para pregunta #{{ pregunta.id }}</h2>

<h4>{{ pregunta.texto_pregunta }}</h4>

<form action="{% url 'encuestas:opciones' pregunta.id %}" method="post">
    {% csrf_token %}

    {% bootstrap_formset opciones_form %}

    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "floppy-disk" %} Guardar Cambios
    </button>
    {% endbuttons %}
</form>

{% endblock contenido %}

curso/encuestas/templates/encuestas/editar_pregunta.html
{% extends 'encuestas/base.html' %}
{% load bootstrap3 %}

{% block extra-head %}
    {{ form.media }}
{% endblock%}

{% block contenido %}

<h2>Editar pregunta #{{ pregunta.id }}</h2>

<form action="{% url 'encuestas:editar' pregunta.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "floppy-disk" %} Guardar Cambios
    </button>
    {% endbuttons %}
</form>

{% endblock contenido %}

curso/encuestas/templates/encuestas/index.html
{% extends 'encuestas/base.html' %}
{% load bootstrap3 %}

{% block contenido %}
{% autoescape on %}

{% if preguntas_recientes %}
    <h2>Encuestas recientes</h2>
    <ul class="list-group">
    {% for pregunta in preguntas_recientes %}
        <li class="list-group-item clearfix">
            {{ pregunta.texto_pregunta }}
            <div class="btn-group pull-right" role="group" aria-label="Acciones">
                <a class="btn btn-primary" role="button"
                href="{% url 'encuestas:detalle' pregunta.id %}">Votar</a>
                <a class="btn btn-info" role="button"
                href="{% url 'encuestas:resultados' pregunta.id %}">Ver resultados</a>
                <a class="btn btn-default" role="button"
                href="{% url 'encuestas:editar' pregunta.id %}">
                    {% bootstrap_icon "pencil" %} Editar Pregunta</a>
            </div>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas disponibles.</p>
{% endif %}

    <a class="btn btn-default" role="button"
    href="{% url 'encuestas:agregar' %}">{% bootstrap_icon "plus" %} Nueva Encuesta</a>

{% endautoescape %}
{% endblock contenido %}

curso/encuestas/templates/encuestas/login.html
{% extends 'encuestas/base.html' %}
{% load bootstrap3 %}

{% block contenido %}

{% if form.errors %}
    {% bootstrap_alert 'Las credenciales son inválidas' alert_type='danger' %}
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
        {% bootstrap_alert 'No posee privilegios para acceder a esta funcionalidad' alert_type='danger' %}
    {% else %}
        {% bootstrap_alert 'Inicie sesión para acceder a esta funcionalidad' alert_type='warning' %}
    {% endif %}
{% endif %}

{% if user.is_authenticated %}
        {% bootstrap_alert 'Ya ha iniciado sesión' alert_type='info' %}
{% else %}
<h2>Iniciar sesión</h2>
<form method="post" action="{% url 'django.contrib.auth.views.login' %}"  class="form-inline">
{% csrf_token %}
{% bootstrap_field form.username layout='inline' %}
{% bootstrap_field form.password layout='inline' %}
{% bootstrap_button "Iniciar sesión" button_type="submit" button_class="btn-primary" %}
<input type="hidden" name="next" value="{{ next }}" />
</form>
{% endif %}

{% endblock %}

curso/encuestas/templates/encuestas/resultados.html
{% extends 'encuestas/base.html' %}

{% block encabezado %}
<h1>Resultados de Encuesta: {{ pregunta.texto_pregunta|truncatewords:5|escape }}...</h1>
{% endblock encabezado %}

{% block contenido %}

<div class="panel panel-primary">
    <div class="panel-heading">Resultados</div>
    <div class="panel-body">
        <h2>{{ pregunta.texto_pregunta|escape }}</h2>

        <ul class="list-group">
        {% for opcion in pregunta.opcion_set.all %}
            <li class="list-group-item">
                <span class="badge">{{ opcion.votos }}</span>
                {{ opcion.texto_opcion }}</li>
        {% endfor %}
        </ul>
    </div>
</div>

<a class="btn btn-primary" href="{% url 'encuestas:detalle' pregunta.id %}">
    Votar
</a>

{% endblock contenido %}